In [2]:
print("hello tensorflow2 👋")

hello tensorflow2 👋


In [4]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [7]:
# load MNIST dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [10]:
# build the model
model = tf.keras.models.Sequential(
    [
     tf.keras.layers.Flatten(input_shape=(28, 28)),
     tf.keras.layers.Dense(128, activation='relu'),
     tf.keras.layers.Dropout(0.2),
     tf.keras.layers.Dense(10),
    ]
)

In [12]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.17078039, -1.0955958 , -0.20024869, -0.07856199,  0.39482567,
         0.90341824,  0.1532701 ,  0.38146445,  0.64190114, -0.87536967]],
      dtype=float32)

In [14]:
# convert it as probabilitites by softmax
tf.nn.softmax(predictions).numpy()

array([[0.09753131, 0.02748931, 0.06729893, 0.07600743, 0.12202412,
        0.2029199 , 0.09583838, 0.12040456, 0.15622452, 0.03426154]],
      dtype=float32)

In [15]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [16]:
loss_fn(y_train[:1], predictions).numpy()

1.594944

In [17]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [18]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2955 - accuracy: 0.9140
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1421 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1077 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0873 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0754 - accuracy: 0.9758


In [20]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0828 - accuracy: 0.9759


[0.08281046152114868, 0.9758999943733215]

In [21]:
probability_model = tf.keras.Sequential(
    [
     model,
     tf.keras.layers.Softmax(),
    ]
)

In [22]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.79915290e-07, 3.18904121e-08, 1.06507525e-06, 3.70122871e-05,
        1.94827862e-10, 1.36900283e-07, 1.13191737e-13, 9.99957204e-01,
        7.45322204e-09, 4.51373444e-06],
       [1.93787155e-08, 5.49374745e-05, 9.99921679e-01, 2.23588086e-05,
        7.13696748e-15, 7.53697009e-07, 1.42403476e-08, 1.65940815e-13,
        2.67818166e-07, 1.27359857e-14],
       [3.21459908e-07, 9.99746978e-01, 8.40895154e-06, 2.42871670e-06,
        4.43440840e-05, 4.03824697e-06, 5.12729457e-06, 1.13473005e-04,
        7.44750578e-05, 4.25984581e-07],
       [9.99635696e-01, 5.36746168e-11, 3.14475968e-04, 3.30499302e-06,
        2.22187296e-07, 1.39987333e-06, 1.97879053e-05, 2.39574933e-06,
        2.98266855e-07, 2.23565075e-05],
       [2.61513122e-07, 1.38107026e-09, 1.34884003e-05, 9.22957142e-08,
        9.98786509e-01, 1.45686379e-08, 1.12935697e-06, 3.56211822e-05,
        6.86592969e-08, 1.16281607e-03]], dtype=float32)>